obstacle_type: broad
sampling_steps: 256
time_discretization: uniform
time_discretization_kwargs:
  prior_time_offset: 0.001
sampler_interpolation_coeff: 1.0
env_objective: []
env_constraints:
  - dynamics
  - ellipses
proxy_objective_value_weight: 2.0
proxy_constraint_penalty_weight: 0.1
constraint_margin: 0.4
policy_kwargs:
  # Values adapted from discrete to continuous time formulation with time convention reversal [0 -> 1]
  cbf_coefficient: 256.0
  guidance_start_fraction: 0.5
  allow_qp: false                  # Enable qp solver isntead of ipopt; for narrow qpth seems unreliable and fails silently
  # ipopt_options: (Table 1 -- older faster options in narrow env)
  #   ipopt.hessian_approximation: limited-memory
  #   ipopt.max_iter: 200
  #   ipopt.acceptable_constr_viol_tol: 5.0e-3
  #   ipopt.acceptable_tol: 1.0e-1
  #   ipopt.acceptable_dual_inf_tol: 1.0e-1
  #   ipopt.acceptable_iter: 1
